export const dummyResponse = {
  kind: 'customsearch#search',
  url: {
    type: 'application/json',
    template:
      'https://www.googleapis.com/customsearch/v1?q={searchTerms}&num={count?}&start={startIndex?}&lr={language?}&safe={safe?}&cx={cx?}&sort={sort?}&filter={filter?}&gl={gl?}&cr={cr?}&googlehost={googleHost?}&c2coff={disableCnTwTranslation?}&hq={hq?}&hl={hl?}&siteSearch={siteSearch?}&siteSearchFilter={siteSearchFilter?}&exactTerms={exactTerms?}&excludeTerms={excludeTerms?}&linkSite={linkSite?}&orTerms={orTerms?}&relatedSite={relatedSite?}&dateRestrict={dateRestrict?}&lowRange={lowRange?}&highRange={highRange?}&searchType={searchType}&fileType={fileType?}&rights={rights?}&imgSize={imgSize?}&imgType={imgType?}&imgColorType={imgColorType?}&imgDominantColor={imgDominantColor?}&alt=json',
  },
  queries: {
    previousPage: [
      {
        title: 'Google Custom Search - next js',
        totalResults: '13660000000',
        searchTerms: 'next js',
        count: 10,
        inputEncoding: 'utf8',
        outputEncoding: 'utf8',
        safe: 'off',
        cx: 'd7ab470542c6e4252',
        searchType: 'image',
      },
    ],
    request: [
      {
        title: 'Google Custom Search - next js',
        totalResults: '13660000000',
        searchTerms: 'next js',
        count: 10,
        startIndex: 10,
        inputEncoding: 'utf8',
        outputEncoding: 'utf8',
        safe: 'off',
        cx: 'd7ab470542c6e4252',
        searchType: 'image',
      },
    ],
    nextPage: [
      {
        title: 'Google Custom Search - next js',
        totalResults: '13660000000',
        searchTerms: 'next js',
        count: 10,
        startIndex: 20,
        inputEncoding: 'utf8',
        outputEncoding: 'utf8',
        safe: 'off',
        cx: 'd7ab470542c6e4252',
        searchType: 'image',
      },
    ],
  },
  context: {
    title: 'go-clone',
  },
  searchInformation: {
    searchTime: 0.452551,
    formattedSearchTime: '0.45',
    totalResults: '13660000000',
    formattedTotalResults: '13,660,000,000',
  },
  items: [
    {
      kind: 'customsearch#result',
      title: 'Different forms of Pre-rendering in NextJS - GeeksforGeeks',
      htmlTitle: 'Different forms of Pre-rendering in <b>NextJS</b> - GeeksforGeeks',
      link: 'https://media.geeksforgeeks.org/wp-content/cdn-uploads/20220311094051/user-can-now-Interact.png',
      displayLink: 'www.geeksforgeeks.org',
      snippet: 'Different forms of Pre-rendering in NextJS - GeeksforGeeks',
      htmlSnippet: 'Different forms of Pre-rendering in <b>NextJS</b> - GeeksforGeeks',
      mime: 'image/png',
      fileFormat: 'image/png',
      image: {
        contextLink: 'https://www.geeksforgeeks.org/different-forms-of-pre-rendering-in-nextjs/',
        height: 628,
        width: 1000,
        byteSize: 96570,
        thumbnailLink:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCOht3yzM5QnoyLygtZYn8priqkToxPt5u5_lmj6mwg2BZCElTUhw7IEQ&s',
        thumbnailHeight: 94,
        thumbnailWidth: 149,
      },
    },
    {
      kind: 'customsearch#result',
      title: 'Blog - Layouts RFC | Next.js',
      htmlTitle: 'Blog - Layouts RFC | <b>Next</b>.<b>js</b>',
      link: 'https://nextjs.org/_next/image?url=%2Fstatic%2Fblog%2Flayouts-rfc%2Frouting-today.png&w=3840&q=75',
      displayLink: 'nextjs.org',
      snippet: 'Blog - Layouts RFC | Next.js',
      htmlSnippet: 'Blog - Layouts RFC | <b>Next</b>.<b>js</b>',
      mime: 'image/',
      fileFormat: 'image/',
      image: {
        contextLink: 'https://nextjs.org/blog/layouts-rfc',
        height: 605,
        width: 1798,
        byteSize: 102412,
        thumbnailLink:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTvGNaahTJSJeu0Pziwebv3Vt73qFryQcNZCY1jBzkHoh9DcmYKg-Ex4Y&s',
        thumbnailHeight: 50,
        thumbnailWidth: 150,
      },
    },
    {
      kind: 'customsearch#result',
      title: "Exploiting Web3's Hidden Attack Surface: Universal XSS on ...",
      htmlTitle: 'Exploiting Web3&#39;s Hidden Attack Surface: Universal XSS on ...',
      link: 'https://samcurry.net/wp-content/uploads/2022/08/1644864897-next-framework.jpeg',
      displayLink: 'samcurry.net',
      snippet: "Exploiting Web3's Hidden Attack Surface: Universal XSS on ...",
      htmlSnippet: 'Exploiting Web3&#39;s Hidden Attack Surface: Universal XSS on ...',
      mime: 'image/jpeg',
      fileFormat: 'image/jpeg',
      image: {
        contextLink: 'https://samcurry.net/universal-xss-on-netlifys-next-js-library/',
        height: 589,
        width: 900,
        byteSize: 54226,
        thumbnailLink:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQz8wVL-DY8xiooNhvzBtusRTDiU8S3E9lhpPps6K9yqOltHrLyHTBoLDA&s',
        thumbnailHeight: 96,
        thumbnailWidth: 146,
      },
    },
    {
      kind: 'customsearch#result',
      title: 'Two Forms of Pre-rendering - Pre-rendering and Data Fetching ...',
      htmlTitle: 'Two Forms of Pre-rendering - Pre-rendering and Data Fetching ...',
      link: 'https://nextjs.org/static/images/learn/data-fetching/server-side-rendering.png',
      displayLink: 'nextjs.org',
      snippet: 'Two Forms of Pre-rendering - Pre-rendering and Data Fetching ...',
      htmlSnippet: 'Two Forms of Pre-rendering - Pre-rendering and Data Fetching ...',
      mime: 'image/png',
      fileFormat: 'image/png',
      image: {
        contextLink: 'https://nextjs.org/learn/basics/data-fetching/two-forms',
        height: 800,
        width: 1386,
        byteSize: 17548,
        thumbnailLink:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCgerOWfUSIhqqz5Ji-0DcW0SB6bkmYLyx5aSMZB81tjBwrSSiFAChVPc&s',
        thumbnailHeight: 87,
        thumbnailWidth: 150,
      },
    },
    {
      kind: 'customsearch#result',
      title: 'Find your Template – Vercel',
      htmlTitle: 'Find your Template – Vercel',
      link: 'https://vercel.com/_next/image?url=https%3A%2F%2Fimages.ctfassets.net%2Fe5382hct74si%2F29l0UrpsQB6uDlmShjiJ72%2Ff44f1f951062bcefa9959e1985cb61af%2FLightMode_CreateNextApp.png&w=3840&q=75',
      displayLink: 'vercel.com',
      snippet: 'Find your Template – Vercel',
      htmlSnippet: 'Find your Template – Vercel',
      mime: 'image/',
      fileFormat: 'image/',
      image: {
        contextLink: 'https://vercel.com/templates',
        height: 1692,
        width: 2540,
        byteSize: 434192,
        thumbnailLink:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRN-RtWFAWud5Zh2UomdJELNpBWUcBOVkalpMcXjLb5X0SwZoTXRiuB_Q&s',
        thumbnailHeight: 100,
        thumbnailWidth: 150,
      },
    },
    {
      kind: 'customsearch#result',
      title: 'Build and Deploy Serverless Apps with Next.js 8 and Zeit Now',
      htmlTitle: 'Build and Deploy Serverless Apps with <b>Next</b>.<b>js</b> 8 and Zeit Now',
      link: 'https://hasura.io/blog/content/images/2019/02/nextjs-serverless-now-hasura-graphql.png',
      displayLink: 'hasura.io',
      snippet: 'Build and Deploy Serverless Apps with Next.js 8 and Zeit Now',
      htmlSnippet: 'Build and Deploy Serverless Apps with <b>Next</b>.<b>js</b> 8 and Zeit Now',
      mime: 'image/png',
      fileFormat: 'image/png',
      image: {
        contextLink:
          'https://hasura.io/blog/build-and-deploy-serverless-apps-with-nextjs-8-zeit-now/',
        height: 675,
        width: 1200,
        byteSize: 46939,
        thumbnailLink:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ290cQAaV9BsU7w1bkL1LMGPieAhrVNQ7MI9t62KOKmk8LPCt7yQBVSGc&s',
        thumbnailHeight: 84,
        thumbnailWidth: 150,
      },
    },
    {
      kind: 'customsearch#result',
      title: 'The best open-source headless CMS for Next.js',
      htmlTitle: 'The best open-source headless CMS for <b>Next</b>.<b>js</b>',
      link: 'https://assets.strapi.io/uploads/next_js_0b25700027.png',
      displayLink: 'strapi.io',
      snippet: 'The best open-source headless CMS for Next.js',
      htmlSnippet: 'The best open-source headless CMS for <b>Next</b>.<b>js</b>',
      mime: 'image/png',
      fileFormat: 'image/png',
      image: {
        contextLink: 'https://strapi.io/integrations/nextjs-cms',
        height: 410,
        width: 784,
        byteSize: 36564,
        thumbnailLink:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRokC5Xwb0P_kv29UOx5k7-lXwVooAAu_CGB2nDNH92bmDeRTvN0iDsUzc&s',
        thumbnailHeight: 75,
        thumbnailWidth: 143,
      },
    },
    {
      kind: 'customsearch#result',
      title: 'Blog - Next.js 8 | Next.js',
      htmlTitle: 'Blog - <b>Next</b>.<b>js</b> 8 | <b>Next</b>.<b>js</b>',
      link: 'https://nextjs.org/_next/image?url=%2Fstatic%2Fblog%2Fnext-8%2Fflow.jpg&w=1080&q=75',
      displayLink: 'nextjs.org',
      snippet: 'Blog - Next.js 8 | Next.js',
      htmlSnippet: 'Blog - <b>Next</b>.<b>js</b> 8 | <b>Next</b>.<b>js</b>',
      mime: 'image/',
      fileFormat: 'image/',
      image: {
        contextLink: 'https://nextjs.org/blog/next-8',
        height: 1061,
        width: 966,
        byteSize: 65749,
        thumbnailLink:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcST55BQFAiBzxaklm5TYjeHEcLfEgPwKQRsEFoUyIVwBeNffjZBLbQGO9Gb&s',
        thumbnailHeight: 150,
        thumbnailWidth: 137,
      },
    },
    {
      kind: 'customsearch#result',
      title: 'How to Build Scalable Architecture for your Next.js Project - DEV ...',
      htmlTitle:
        'How to Build Scalable Architecture for your <b>Next</b>.<b>js</b> Project - DEV ...',
      link: 'https://i.ytimg.com/vi/Iu5aZDqZt8E/maxresdefault.jpg',
      displayLink: 'dev.to',
      snippet: 'How to Build Scalable Architecture for your Next.js Project - DEV ...',
      htmlSnippet:
        'How to Build Scalable Architecture for your <b>Next</b>.<b>js</b> Project - DEV ...',
      mime: 'image/jpeg',
      fileFormat: 'image/jpeg',
      image: {
        contextLink:
          'https://dev.to/alexeagleson/how-to-build-scalable-architecture-for-your-nextjs-project-2pb7',
        height: 720,
        width: 1280,
        byteSize: 106728,
        thumbnailLink:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRn6FgjJQiW3-zgTqnuvIXnNh92KdkGoc23a5YQVMGg6Cc1sYMRvm0yQNA&s',
        thumbnailHeight: 84,
        thumbnailWidth: 150,
      },
    },
    {
      kind: 'customsearch#result',
      title: 'Build a Full Stack App with Next.js, Tailwind, tRPC and Prisma ORM ...',
      htmlTitle:
        'Build a Full Stack App with <b>Next</b>.<b>js</b>, Tailwind, tRPC and Prisma ORM ...',
      link: 'https://res.cloudinary.com/practicaldev/image/fetch/s--BMWspgKL--/c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/ds4yi6va1jyjhyfroddl.png',
      displayLink: 'dev.to',
      snippet: 'Build a Full Stack App with Next.js, Tailwind, tRPC and Prisma ORM ...',
      htmlSnippet:
        'Build a Full Stack App with <b>Next</b>.<b>js</b>, Tailwind, tRPC and Prisma ORM ...',
      mime: 'image/png',
      fileFormat: 'image/png',
      image: {
        contextLink:
          'https://dev.to/franciscomendes10866/build-a-full-stack-app-with-nextjs-tailwind-trpc-and-prisma-orm-4ail',
        height: 420,
        width: 1000,
        byteSize: 78688,
        thumbnailLink:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQb8k-kenR7uat39jcLyAnIhS1xAkoRxHmbGpMaZItTD3PFBOtSBYrP_Q&s',
        thumbnailHeight: 63,
        thumbnailWidth: 149,
      },
    },
  ],
};
