import Header from '@/components/Header';
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google Clone</title>
        <meta name='description' content='Generated By Next js' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main></main>
    </div>
  );
}
